db:
  host: db
  port: 5432
  database: scade
  password: scade
  username: scade

redis:
  host: redis
  port: 6379
  password:
  database: 1

sockets:
  ip: 127.0.0.1
  port: 3001

rpc:
  ip: 127.0.0.1
  port: 5500